language: ruby
rvm: 2.2
sudo: false
cache:
  directories:
    - vendor/bundle
    - $HOME/.npm
before_install: |
  npm install -g gitbook-cli
  bundle install --deployment --jobs=3 --retry=3
script: test $TRAVIS_PULL_REQUEST != "false" || test $TRAVIS_BRANCH != "translation" || ./travis-build.sh
branches:
  only:
    - translation
